# CHANGE_LOG.toml

# A structured for API Endpoint Adds and Changes
# Dateformat: DD.MM.YYYY

[[routes]]
file = "node/server3000.js"
description = "Test endpoint for API testing."
method = "GET"
path = "/api/test"
create_date = "11.11.2025"

[[routes]]
file = "node/server3000.js"
description = "User login endpoint."
method = "POST"
path = "/api/login"
create_date = "12.11.2025"

[[routes]]
file = "node/server3000.js"
description = "Setup endpoint for initial configuration."
method = "POST"
path = "/api/setup"
create_date = "17.11.2025"

[[routes]]
file = "node/server3000.js"
description = "Create a new user for an existing company"
method = "POST"
path = "/api/users"
create_date = "01.12.2025"

[[routes]]
file = "node/server3000.js"
description = "Mimo Chatbot for questions about SentinelIS"
method = "POST"
path = "/api/chatbot"
create_date = "03.12.2025"

[[routes]]
file = "node/server5000.js"
description = "Create a new asset"
method = "POST"
path = "/api/assets"
create_date = "06.01.2026"

[[routes]]
file = "node/server5000.js"
description = "Get asset details by asset_id"
method = "GET"
path = "/api/assets/:id"
create_date = "07.01.2026"

[[routes]]
file = "node/server5000.js"
description = "Update asset details by asset_id"
method = "PUT"
path = "/api/assets/:id"
create_date = "07.01.2026"

[[routes]]
file = "node/server5000.js"
description = "Delete asset by asset_id"
method = "DELETE"
path = "/api/assets/:id"
create_date = "07.01.2026"